name: CD Pipeline Backend CTG Raizes

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Navega até a pasta do backend no servidor
            cd /home/ti/site-php/www/back-ctgraizes
            
            # 2. Puxa as últimas atualizações do GitHub
            git pull origin main
            
            # 3. Executa as migrations do banco de dados em ordem alfabética/numérica
            echo "Iniciando verificação de migrations..."
            
            for sql_file in $(ls src/Database/migrations/*.sql | sort); do
              echo "Aplicando: $sql_file"
              
              # O '|| true' no final garante que se a tabela já existir, a esteira não vai quebrar
              docker exec -i mysql_db_php mysql -uroot -pexemplo123 phpdb < "$sql_file" || true
            done
            
            echo "Deploy e Migrations finalizados com sucesso!"
